# fly.toml app configuration file generated for zyppts-logo-processor-aged-violet-9912 on 2025-08-07T02:32:03-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zyppts-logo-processor-aged-violet-9912'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  CACHE_TYPE = 'redis'
  FLASK_DEBUG = 'False'
  FLASK_ENV = 'production'
  LOG_LEVEL = 'INFO'
  MAX_CONTENT_LENGTH = '16777216'
  PLATFORM = 'fly'
  PYTHON_VERSION = '3.11.0'
  SESSION_COOKIE_SECURE = 'True'
  SESSION_TYPE = 'redis'
  UPLOAD_EXTENSIONS = '.png,.jpg,.jpeg,.gif,.bmp,.tiff,.svg,.pdf,.webp'

[processes]
  app = 'gunicorn --bind 0.0.0.0:8080 --workers 2 --worker-class sync --timeout 90 --keep-alive 2 --max-requests 500 --max-requests-jitter 50 --worker-tmp-dir /tmp --preload Backend.app_config:create_app()'

[[mounts]]
  source = 'zyppts_data'
  destination = '/app/data'

# HTTP Service Configuration
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.ports]]
    port = 80
    handlers = ["http"]

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'

[checks]
  [checks.app]
    port = 8080
    type = 'http'
    interval = '15s'
    timeout = '5s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048

[[metrics]]
  port = 9091
  path = '/metrics'
